CREATE TABLE BBS02 
(
  NUM NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, SUB VARCHAR2(50) 
, CONTENT VARCHAR2(2000) 
, NALJA DATE 
, CONSTRAINT BBS02_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);